pages:
  image: node:latest
  stage: deploy
  script:
    - cd svelte-app
    - npm install
    - npm run build
  artifacts:
    paths:
      - svelte-app/.svelte-kit/build
  only:
    - main
    - dev
