# variables:
#   CARGO_HOME: $CI_PROJECT_DIR/wasm/.cargo


# .wasm_cache:
#   cache:
#     key: "rust-wasm-build"
#     paths:
#       - wasm/target/
#       - wasm/pkg/
#       - $CARGO_HOME
#     policy: pull
#   before_script:
#     # Show cache size, but if dirs not found just show the error without crashing the CI job
#     - du -sh wasm/target wasm/pkg $CARGO_HOME || true


# # Build job also installs linting/testing tools used by other jobs
# svelte-wasmbuild:
#   extends: .wasm_cache
#   image: rust:1.61
#   before_script:
#     - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
#   script:
#     - wasm-pack -v build wasm --target web
#   cache:
#     policy: pull-push


# svelte-build:
#   extends: .wasm_cache
#   needs: [svelte-wasmbuild]
#   image: node:16
#   script:
#     - cd svelte-app
#     - yarn
#     - yarn build


typescript-test:
  image: node:16
  before_script:
    - cd svelte-app
    - yarn --dev
  script:
    - yarn test --ci --reporters=default --reporters=jest-junit --coverage
  artifacts:
    reports:
      junit:
        - svelte-app/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: svelte-app/coverage/clover.xml
