variables:
  CARGO_HOME: $CI_PROJECT_DIR/wasm/.cargo


.rust_cached:
  image: rust:1.61
  cache:
    key: "rust-build"
    paths:
      - wasm/target/
      - $CARGO_HOME
    policy: pull
  before_script:
    # Show cache size, but if dirs not found just show the error without crashing the CI job
    - du -sh wasm/target $CARGO_HOME || true


wasm-build:
  extends: .rust_cached
  script:
    - cd wasm
    - cargo build
  cache:
    policy: pull-push


wasm-rustfmt:
  image: rust:1.61
  before_script:
    - rustup component add rustfmt
  script:
    - cd wasm
    - cargo fmt --check


wasm-clippy:
  needs: [wasm-build]
  extends: .rust_cached
  before_script:
    - rustup component add clippy
  script:
    - cd wasm
    - cargo clippy -- -D warnings -D clippy::unwrap_used -D clippy::expect_used


wasm-test:
  needs: [wasm-build]
  extends: .rust_cached
  before_script:
    - wget -qO- https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz | tar -xz -C /usr/bin
    - mkdir -p $CARGO_HOME/bin
    - if [ ! -e "$CARGO_HOME/bin/cargo-tarpaulin" ]; then cargo binstall --no-confirm --install-path $CARGO_HOME/bin cargo-tarpaulin; fi
    - if [ ! -e "$CARGO_HOME/bin/cargo-nextest" ]; then cargo binstall --no-confirm --install-path $CARGO_HOME/bin cargo-nextest; fi
  script:
    - cd wasm
    - cargo nextest run
    - cargo tarpaulin --skip-clean -o xml
  artifacts:
    reports:
      junit:
        - wasm/target/nextest/default/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: wasm/cobertura.xml
