# TODO: add a step that compiles for wasm target?
# TODO: caching dependencies doesn't work for some reason??
wasm-build:
  image: rust:1.60
  script:
    - cd wasm
    - cargo build
  # cache:
  #   key: "$CI_COMMIT_REF_NAME"
  #   policy: push
  #   paths:
  #     - wasm/target/
  #     - /root/.cargo/registry/index/


wasm-rustfmt:
  image: rust:1.60
  script:
    - cd wasm
    - rustup component add rustfmt
    - cargo fmt --check
  allow_failure: true


wasm-clippy:
  image: rust:1.60
  # needs: [wasm-build]
  script:
    - cd wasm
    - rustup component add clippy
    - cargo clippy -- -D warnings
  # cache:
  #   key: "$CI_COMMIT_REF_NAME"
  #   policy: pull
  #   paths:
  #     - wasm/target/
  #     - /root/.cargo/registry/index/
  allow_failure: true


wasm-test:
  image: rust:1.60
  # needs: [wasm-build]
  script:
    - wget -qO- https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz | tar -xz -C /usr/bin
    - cargo binstall --no-confirm cargo-tarpaulin && cargo binstall --no-confirm cargo-nextest
    - cd wasm
    - cargo nextest run
    - cargo tarpaulin --skip-clean
  # cache:
  #   key: "$CI_COMMIT_REF_NAME"
  #   policy: pull
  #   paths:
  #     - wasm/target/
  #     - /root/.cargo/registry/index/
