variables:
  CARGO_HOME: $CI_PROJECT_DIR/wasm/.cargo


stages:
  - build
  - test


.rust_cached:
  image: rust:1.61
  cache:
    key: "rust-build"
    paths:
      - wasm/target/
      - $CARGO_HOME
    policy: pull-push
  before_script:
    - du -sh wasm/target
    - du -sh $CARGO_HOME


wasm-build:
  extends: .rust_cached
  stage: build
  script:
    - cd wasm
    - cargo build


wasm-rustfmt:
  image: rust:1.61
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cd wasm
    - cargo fmt --check


wasm-clippy:
  extends: .rust_cached
  stage: test
  before_script:
    - rustup component add clippy
  script:
    - cd wasm
    - cargo clippy -- -D warnings -D clippy::unwrap_used -D clippy::expect_used


wasm-test:
  extends: .rust_cached
  stage: test
  before_script:
    - wget -qO- https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz | tar -xz -C /usr/bin
    - mkdir -p $CARGO_HOME/bin
    - if [ ! -e "$CARGO_HOME/bin/cargo-tarpaulin" ]; then cargo binstall --no-confirm --install-path $CARGO_HOME/bin cargo-tarpaulin; fi
    - if [ ! -e "$CARGO_HOME/bin/cargo-nextest" ]; then cargo binstall --no-confirm --install-path $CARGO_HOME/bin cargo-nextest; fi
  script:
    - cd wasm
    - cargo nextest run
    - cargo tarpaulin --skip-clean
