variables:
  CARGO_HOME: $CI_PROJECT_DIR/wasm/.cargo


wasm-rustfmt:
  image: rust:1.61
  before_script:
    - rustup component add rustfmt
  script:
    - cd wasm
    - cargo fmt --check


wasm-clippy:
  image: rust:1.61
  before_script:
    - rustup component add clippy
  script:
    - cd wasm
    - cargo clippy -- -D warnings -D clippy::unwrap_used -D clippy::expect_used
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - wasm/target/
      - $CARGO_HOME


wasm-test:
  image: rust:1.61
  before_script:
    - wget -qO- https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz | tar -xz -C /usr/bin
    - mkdir -p $CARGO_HOME/bin
    - if [ ! -e "$CARGO_HOME/bin/cargo-tarpaulin" ]; then cargo binstall --no-confirm --install-path $CARGO_HOME/bin --log-level debug cargo-tarpaulin; fi
    - if [ ! -e "$CARGO_HOME/bin/cargo-nextest" ]; then cargo binstall --no-confirm --install-path $CARGO_HOME/bin --log-level debug cargo-nextest; fi
  script:
    - cd wasm
    - cargo nextest run
    - cargo tarpaulin --skip-clean
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - wasm/target/
      - $CARGO_HOME
