wasm-rustfmt:
  image: rust:1.61
  script:
    - cd wasm
    - rustup component add rustfmt
    - cargo fmt --check
  allow_failure: true


wasm-clippy:
  image: rust:1.61
  script:
    - cd wasm
    - rustup component add clippy
    - cargo clippy -- -D warnings -D clippy::unwrap_used -D clippy::expect_used
  allow_failure: true


wasm-test:
  image: rust:1.61
  script:
    - wget -qO- https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz | tar -xz -C /usr/bin
    - cargo binstall --no-confirm cargo-tarpaulin && cargo binstall --no-confirm cargo-nextest
    - cd wasm
    - cargo nextest run
    - cargo tarpaulin --skip-clean
